defmodule SymphonyElixir.TaskContextPromptTest do
  use ExUnit.Case, async: true

  alias SymphonyElixir.Linear.{Comment, Issue}
  alias SymphonyElixir.TaskContextPrompt

  test "renders issue details, current activity, and annotated startup artifacts in order" do
    issue = %Issue{
      identifier: "UDPE-7011",
      title: "Resume after a decision",
      state: "In Progress",
      labels: ["needs-human-input"],
      url: "https://linear.app/example/issue/UDPE-7011",
      description: "Apply the product owner's decision.",
      comments: [
        %Comment{
          id: "comment-1",
          body: "Decision: use option B.",
          author_name: "Product owner",
          created_at: ~U[2026-07-29 10:00:00Z]
        }
      ]
    }

    session_start = %{
      outcome: :passed,
      output: "unstructured hook output",
      workpad_files: [
        "docs/agent-workpad/branch/base-status.md",
        "docs/agent-workpad/branch/reuse-map.md",
        "docs/agent-workpad/branch/custom.md"
      ],
      artifacts: [
        %{
          path: "docs/agent-workpad/branch/base-status.md",
          description: "branch freshness and any required rebase action"
        },
        %{
          path: "docs/agent-workpad/branch/reuse-map.md",
          description: "helper index derived from this issue's title and description"
        },
        %{path: "docs/agent-workpad/branch/custom.md", description: nil}
      ],
      script_timings: []
    }

    prompt = TaskContextPrompt.render(issue, session_start)

    assert prompt =~ "# Task context"
    assert prompt =~ "Issue: UDPE-7011"
    assert prompt =~ "## Current Linear activity"
    assert prompt =~ "Decision: use option B."
    assert prompt =~ "This issue is marked `needs-human-input`"
    assert prompt =~ "## Startup artifacts generated for this task"
    assert prompt =~ "`docs/agent-workpad/branch/base-status.md` — branch freshness and any required rebase action."
    assert prompt =~ "`docs/agent-workpad/branch/reuse-map.md` — helper index derived from this issue's title and description."
    assert prompt =~ "`docs/agent-workpad/branch/custom.md` — generated by the repository's `session_start` hook."
    refute prompt =~ "unstructured hook output"

    {issue_position, _length} = :binary.match(prompt, "Issue: UDPE-7011")
    {activity_position, _length} = :binary.match(prompt, "## Current Linear activity")
    {artifacts_position, _length} = :binary.match(prompt, "## Startup artifacts generated for this task")

    assert issue_position < activity_position
    assert activity_position < artifacts_position
  end

  test "makes an empty activity snapshot explicit and omits absent startup artifacts" do
    prompt = TaskContextPrompt.render(%Issue{identifier: "UDPE-7062", comments: []})

    assert prompt =~ "No Linear comments were present at dispatch."
    refute prompt =~ "Startup artifacts"
  end

  test "surfaces a startup failure as non-blocking structured context" do
    prompt =
      TaskContextPrompt.render(%Issue{identifier: "UDPE-7062"}, %{
        outcome: :failed,
        output: "secret or noisy output",
        workpad_files: [],
        artifacts: [],
        script_timings: []
      })

    assert prompt =~ "informational `session_start` hook failed"
    assert prompt =~ "No startup artifacts were found."
    refute prompt =~ "secret or noisy output"
  end
end
