defmodule SymphonyElixir.TaskContextPromptTest do
  use ExUnit.Case, async: true

  alias SymphonyElixir.Linear.{Comment, Issue}
  alias SymphonyElixir.TaskContextPrompt

  test "renders issue details, current activity, and annotated startup artifacts in order" do
    issue = %Issue{
      identifier: "UDPE-7011",
      title: "Resume after a decision",
      state: "In Progress",
      labels: ["needs-human-input"],
      url: "https://linear.app/example/issue/UDPE-7011",
      attachment_urls: [
        "https://pauca.sentry.io/issues/123456/",
        "https://example.com/design"
      ],
      description: "Apply the product owner's decision.",
      comments: [
        %Comment{
          id: "comment-1",
          body: "Decision: use option B.",
          author_name: "Product owner",
          created_at: ~U[2026-07-29 10:00:00Z]
        }
      ]
    }

    session_start = %{
      outcome: :passed,
      output: "unstructured hook output",
      workpad_files: [
        "docs/agent-workpad/branch/base-status.md",
        "docs/agent-workpad/branch/reuse-map.md",
        "docs/agent-workpad/branch/custom.md"
      ],
      artifacts: [
        %{
          path: "docs/agent-workpad/branch/base-status.md",
          description: "branch freshness and any required rebase action"
        },
        %{
          path: "docs/agent-workpad/branch/reuse-map.md",
          description: "helper index derived from this issue's title and description"
        },
        %{path: "docs/agent-workpad/branch/custom.md", description: nil}
      ],
      script_timings: []
    }

    prompt = TaskContextPrompt.render(issue, session_start)

    assert prompt =~ "# Task context"
    assert prompt =~ "Issue: UDPE-7011"
    assert prompt =~ "## Current Linear activity"
    assert prompt =~ "https://pauca.sentry.io/issues/123456/"
    assert prompt =~ "https://example.com/design"
    assert prompt =~ "Call `get_sentry_resource` with that exact URL"
    assert prompt =~ "Decision: use option B."
    assert prompt =~ "This issue is marked `needs-human-input`"
    assert prompt =~ "## Startup artifacts generated for this task"
    assert prompt =~ "`docs/agent-workpad/branch/base-status.md` — branch freshness and any required rebase action."
    assert prompt =~ "`docs/agent-workpad/branch/reuse-map.md` — helper index derived from this issue's title and description."
    assert prompt =~ "`docs/agent-workpad/branch/custom.md` — generated by the repository's `session_start` hook."
    refute prompt =~ "unstructured hook output"

    {issue_position, _length} = :binary.match(prompt, "Issue: UDPE-7011")
    {activity_position, _length} = :binary.match(prompt, "## Current Linear activity")
    {artifacts_position, _length} = :binary.match(prompt, "## Startup artifacts generated for this task")

    assert issue_position < activity_position
    assert activity_position < artifacts_position
  end

  test "makes an empty activity snapshot explicit and omits absent startup artifacts" do
    prompt = TaskContextPrompt.render(%Issue{identifier: "UDPE-7062", comments: []})

    assert prompt =~ "No Linear comments were present at dispatch."
    assert prompt =~ "Attachments:\nNone"
    refute prompt =~ "Startup artifacts"
  end

  test "surfaces a startup failure as non-blocking structured context" do
    prompt =
      TaskContextPrompt.render(%Issue{identifier: "UDPE-7062"}, %{
        outcome: :failed,
        output: "secret or noisy output",
        workpad_files: [],
        artifacts: [],
        script_timings: []
      })

    assert prompt =~ "informational `session_start` hook failed"
    assert prompt =~ "No startup artifacts were found."
    refute prompt =~ "secret or noisy output"
  end

  test "compresses only equivalent machine review outcomes and preserves human comments" do
    repeated_review = fn id, created_at ->
      %Comment{
        id: id,
        author_name: "UDPAgent",
        created_at: created_at,
        body: """
        <!-- symphony:review-skipped -->
        Automated review outcome: `infrastructure_unavailable` (not approved).

        Candidate SHA: `abc123`
        """
      }
    end

    prompt =
      TaskContextPrompt.render(%Issue{
        identifier: "UDPE-7062",
        comments: [
          repeated_review.("review-old", ~U[2026-08-18 10:00:00Z]),
          %Comment{id: "human-1", author_name: "Reviewer", body: "Please keep both tenant guards."},
          repeated_review.("review-new", ~U[2026-08-19 10:00:00Z]),
          %Comment{id: "workpad", author_name: "UDPAgent", body: "## Codex Workpad\n\nCurrent plan."}
        ]
      })

    refute prompt =~ "id=\"review-old\""
    assert prompt =~ "id=\"review-new\""
    assert prompt =~ "omitted-equivalent-comments=\"1\""
    assert prompt =~ "Please keep both tenant guards."
    assert prompt =~ "## Codex Workpad"
  end

  test "renders only new and updated activity after the previous prompt cursor" do
    original = %Comment{id: "human-1", author_name: "Reviewer", body: "Keep the tenant guard."}
    workpad = %Comment{id: "workpad", author_name: "UDPAgent", body: "## Codex Workpad\n\nOld plan."}
    prior_issue = %Issue{identifier: "UDPE-7062", comments: [original, workpad]}
    prior_state = TaskContextPrompt.put_activity_cursor(%{}, prior_issue)

    changed_issue = %Issue{
      prior_issue
      | comments: [
          original,
          %{workpad | body: "## Codex Workpad\n\nUpdated plan."},
          %Comment{id: "human-2", author_name: "Product owner", body: "Use option B."}
        ]
    }

    delta = TaskContextPrompt.activity_delta_section(changed_issue, prior_state)

    assert delta.content =~ "## Linear activity since the previous turn"
    assert delta.content =~ "Updated plan."
    assert delta.content =~ "Use option B."
    refute delta.content =~ "Keep the tenant guard."
  end
end
